# Generated by Django 5.1.3 on 2025-01-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesanan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='stok_terupdate',
            field=models.BooleanField(default=False),
        ),
    ]
