# Generated by Django 5.1.3 on 2025-02-01 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menuitem_gambar'),
        ('pesanan', '0002_pesanan_stok_terupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='menu',
            field=models.ForeignKey(db_column='idmenu', on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem'),
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
