# Generated by Django 5.1.3 on 2025-02-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesanan', '0003_alter_pesanan_menu_delete_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='status_pesanan',
            field=models.CharField(choices=[('Baru', 'Baru'), ('Diproses', 'Diproses'), ('Disajikan', 'Disajikan')], default='Baru', max_length=50),
        ),
    ]
