# Generated by Django 5.1.3 on 2025-02-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesanan', '0004_pesanan_status_pesanan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='status_pesanan',
            field=models.CharField(choices=[('-', '-'), ('Baru', 'Baru'), ('Diproses', 'Diproses'), ('Disajikan', 'Disajikan')], default='-', max_length=50),
        ),
    ]
