# Generated by Django 5.1.3 on 2025-01-20 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanKeuangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('nomor_order', models.CharField(max_length=50)),
                ('layanan', models.CharField(max_length=50)),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('metode_bayar', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesanan', models.JSONField(default=dict)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('nomor_order', models.CharField(max_length=20)),
                ('layanan', models.CharField(max_length=50)),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_bayar', models.CharField(choices=[('Lunas', 'Lunas'), ('Belum', 'Belum')], max_length=10)),
                ('metode_bayar', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_pesanan', to='menu.menuitem')),
            ],
        ),
    ]
