# Generated by Django 5.1.3 on 2025-01-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporankeuangan',
            name='tanggal',
            field=models.DateField(auto_now_add=True),
        ),
    ]
