# Generated by Django 5.1.3 on 2025-01-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0002_alter_laporankeuangan_tanggal'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20)),
                ('nama_item', models.CharField(max_length=100)),
                ('jumlah_terjual', models.PositiveIntegerField(default=0)),
                ('tanggal', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
