# Generated by Django 5.0.6 on 2025-01-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('idmenu', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('nama_item', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kategori', models.CharField(max_length=100)),
                ('stok_saat_ini', models.IntegerField(default=0)),
                ('stok_terjual', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'menu_item',
            },
        ),
    ]
