# Generated by Django 5.1.3 on 2025-01-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_stoklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='gambar',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
