# Generated by Django 5.1.3 on 2025-02-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitem_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='gambar',
            field=models.URLField(blank=True, default='', max_length=300, null=True),
        ),
    ]
